package views;

import controllers.LoginController;
import java.awt.Color;
import java.util.concurrent.ExecutionException;
import models.UserModel;
import utils.ImagesOfProject;
import utils.ProcessStates;

/**
 * @author mdark
 */

public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.configureComponents();
    }
    
    public final void configureComponents(){
        hintUser.grabFocus();
        btnRegister.setForeground( new Color(120, 223, 203, 100) );
        clearErrors();
        labelLogo.setIcon(ImagesOfProject.getLogoBack() );
        labelPeople.setIcon(ImagesOfProject.getPeople());
        
    }
    
    public void clearErrors(){
        errorMessage.setText("");
        errorMessage.setForeground( new Color(255, 102, 102, 255) );
        errorUser.setVisible(false);
        errorPassword.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelPeople = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        errorUser = new javax.swing.JSeparator();
        txtUser = new javax.swing.JTextField();
        errorPassword = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        RBMostrar = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JLabel();
        hintUser = new javax.swing.JLabel();
        hintPassword = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(110, 223, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 130, 160));

        labelPeople.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 340, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 490));

        jPanel2.setBackground(new java.awt.Color(55, 73, 97));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorUser.setBackground(new java.awt.Color(255, 0, 51));
        errorUser.setForeground(new java.awt.Color(255, 51, 51));
        errorUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 5));
        errorUser.setPreferredSize(new java.awt.Dimension(50, 3));
        jPanel2.add(errorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 127, 290, -1));

        txtUser.setBackground(new java.awt.Color(65, 87, 117));
        txtUser.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUser.setName(""); // NOI18N
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 50));
        txtUser.getAccessibleContext().setAccessibleDescription("");

        errorPassword.setBackground(new java.awt.Color(255, 0, 51));
        errorPassword.setForeground(new java.awt.Color(255, 51, 51));
        errorPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 5));
        errorPassword.setPreferredSize(new java.awt.Dimension(50, 3));
        jPanel2.add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 228, 290, -1));

        txtPassword.setBackground(new java.awt.Color(65, 87, 117));
        txtPassword.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, 50));

        RBMostrar.setBackground(new java.awt.Color(55, 73, 97));
        RBMostrar.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        RBMostrar.setForeground(new java.awt.Color(255, 255, 255));
        RBMostrar.setText("Mostrar Contraseña");
        RBMostrar.setBorder(null);
        RBMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RBMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(RBMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        btnLogin.setBackground(new java.awt.Color(110, 223, 203));
        btnLogin.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnLogin.setText("Iniciar sesión");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 290, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Aun no tienes cuenta? ");
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorMoved1(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel2MouseWheelMoved(evt);
            }
        });
        jLabel2.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                jLabel2AncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 160, 30));

        btnRegister.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(110, 223, 203));
        btnRegister.setText("Registrarte");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });
        jPanel2.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, 30));

        hintUser.setForeground(new java.awt.Color(255, 255, 255));
        hintUser.setText("Usuario o Email");
        jPanel2.add(hintUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        hintPassword.setForeground(new java.awt.Color(255, 255, 255));
        hintPassword.setText("Contraseña");
        jPanel2.add(hintPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        errorMessage.setForeground(new java.awt.Color(255, 102, 102));
        errorMessage.setText("Error del mensaje");
        errorMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(errorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 60, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 370, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserMouseClicked

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel2AncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel2AncestorMoved

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorMoved

    private void jLabel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel2MouseWheelMoved
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseWheelMoved

    private void jLabel2AncestorMoved1(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorMoved1
  
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorMoved1

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
 
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void RBMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMostrarActionPerformed
        if (RBMostrar.isSelected()==true){
            txtPassword.setEchoChar((char)0);
        } else if (RBMostrar.isSelected()==false){
            txtPassword.setEchoChar('*');
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_RBMostrarActionPerformed

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered

        btnRegister.setForeground( new Color(120, 223, 203, 255) );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterMouseEntered

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        btnRegister.setForeground( new Color(120, 223, 203, 100) );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterMouseExited

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed


    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
      SingUp Show_SingUp = new SingUp();
      Show_SingUp.setVisible(true);
      this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        btnLogin.setText("Cargando...");
        btnLogin.setEnabled(false);
        
        UserModel user = new UserModel(txtUser.getText().trim(), String.valueOf(txtPassword.getPassword()));
        int response = 0;
        
        try {
            response = LoginController.loginWithUserAndPassword(user);
            
        } catch (InterruptedException ex) {
            System.out.println(ex);
            response = ProcessStates.NOT_FOUND;
        } catch (ExecutionException ex) {
            System.out.println(ex);
            response = ProcessStates.NOT_FOUND;
        }
        
        if (response == ProcessStates.OK ) {
            errorMessage.setText("Todo salio bien");
            errorMessage.setForeground(Color.GREEN);
            PrincipalView principal = new PrincipalView();
            principal.setVisible(true);
            this.dispose();
            
        } else if (response == ProcessStates.NOT_FOUND){
            errorMessage.setText("Not matches");
            
        } else {
            
            if (response == ProcessStates.USER_MISSING) {
                errorMessage.setText("User missing");
                errorUser.setVisible(true);
            
            }
            
            if (response == ProcessStates.PASSWORD_MISSING) {
                errorMessage.setText("Password Missing");
                errorPassword.setVisible(true);
            
            }
            
        }

        btnLogin.setText("Iniciar Sesión");
        btnLogin.setEnabled(true);
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    // show or hide hint of the textfields
    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        // TODO add your handling code here:
        clearErrors();
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        clearErrors();
    }//GEN-LAST:event_txtPasswordKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox RBMostrar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JSeparator errorPassword;
    private javax.swing.JSeparator errorUser;
    private javax.swing.JLabel hintPassword;
    private javax.swing.JLabel hintUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPeople;
    private javax.swing.JLabel loading;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
